### ISSUE TITLE
Does this work on for Pi Camera v1 and v2?

### ISSUE THREAD

**Issue by abhishek-nigam** [geerlingguy/pi-webcam#10]
Hi there!
Thanks for making this awesome resource. I just wanted to know if this can be used with other Raspberry Pi camera modules (v1, v2), and could you also elucidate if any changes need to be made to the project to get it to work with them?

**Comment by geerlingguy** [comment]
Yes, it should work with them just as easily. I remember testing the v2 camera at least, just didn't document it anywhere :)

**Comment by abhishek-nigam** [comment]
Great, thanks!

**Comment by sniff122** [comment]
i have this working with the v2 camera, perfect candidate for a down facing camera on my desk, im using a pi zero w with the v2 module
