### ISSUE TITLE
Screen Output

### ISSUE THREAD

**Issue by yeyeto2788** [geerlingguy/pi-webcam#12]
Hey @geerlingguy! Thanks putting all this together.

Any thoughts on adding an option for enabling video output on HDMI or other kind of output (TFT screen)

By reading thought this [gist](https://gist.github.com/justinschuldt/36469e2a89d95ef158a8c4df091e9cb4) having the `video0` means the camera is enabled and that would be the input for the `video1` output which is the one used over USB.

Maybe we can take `video0` also as input for other output like external display. 

If any help is needed just ping me, I can test it on a external TFT if you don't have one.

Regards.

**Comment by GottZ** [comment]
i literally think about using one of these 3.5 inch rpi displays that attaches to gpio. they only provide like 12.5 fps at 480x320 with 16 mil colors tho.. better than nothing i bet.
