### ISSUE TITLE
Works in Windows, Problems in Linux

### ISSUE THREAD

**Issue by ccheath** [geerlingguy/pi-webcam#33]
dmesg:
![image](https://user-images.githubusercontent.com/26904477/106402016-8d147e80-63f5-11eb-885d-bffcd14cfda4.png)

lsusb:
![image](https://user-images.githubusercontent.com/26904477/106402074-cc42cf80-63f5-11eb-86aa-0b8024c2f516.png)

![image](https://user-images.githubusercontent.com/26904477/106402108-fa281400-63f5-11eb-866a-bdf86208fb48.png)

any ideas for troubleshooting?
(and btw, thanks)

**Comment by stephencross** [comment]
Same for me, Works on Mac, not on Ubuntu 20.04

**Comment by maxkueng** [comment]
Can confirm that it works on a Thinkpad T470 with Intel integrated graphics. I don't have a machine with Nvidia graphics to test.
