### ISSUE TITLE
pi zero w freezes when opening camera app on pc

### ISSUE THREAD

**Issue by cnijpels** [geerlingguy/pi-webcam#41]
I followed all instructions and I am able to see the uvc-camera in the device manager.
But when i try to view the video feed, using any camera app (obs, windows camera app etc.), the app instantly freezes and so does the pi.
I also tried multiple usb cables.
Any idea what could cause this?

**Comment by ariel-rl** [comment]
Not sure whether related, but I had an issue with freezing after several minutes of use in obs or skype. The following thread worked for me: https://github.com/raspberrypi/linux/issues/2555

In a nutshell: some issues with pi camera modules with kernel oops, most likely more on pi zero models with H° mark next to camera cable part. seems solvable by adjusting arm frequency in boot config. worked for me with the parameters mentioned in the very last post, no guarantee though.
