### ISSUE TITLE
Configure Camera Settings

### ISSUE THREAD

**Issue by maxkremmel** [geerlingguy/pi-webcam#48]
It would be nice to implement a possibility to configure the Camera. For example, rotate the image by 90 degree or to increase the gain.

**Comment by wytr** [comment]
Could someone give me a hint on where one can look at to try to configure the camera settings? As far as i understand it, the camera ressources are being used by the service/task that is streaming it over USB, so you cant access it over anything else(e.g. piCamera module in python or whatever). Im quite a newbie but got some time on my hands and would by quite thankful for some tips!
