### ISSUE TITLE
ansible-playbook main problem

### ISSUE THREAD

**Issue by bhbloom** [geerlingguy/pi-webcam#62]
**I get this error when running the command  

ansible-playbook main** 

TASK [Clone uvc-gadget to the Pi.] *********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": ["/usr/bin/git", "fetch", "--tags", "origin"], 
"msg": "Failed to download remote objects and refs:  fatal: unterminated line in .git/packed-refs: ...\n"}

**I am running**
ansible [core 2.12.3]
  config file = /home/pi/pi-webcam/ansible.cfg
  configured module search path = ['/home/pi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/pi/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Mar 12 2021, 04:06:34) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True

I dont know how to proceed.

**Comment by qlkv** [comment]
I have exactly the same issue
