### ISSUE TITLE
Task [Clone uvc-gadget to the pi.] FAILED! permission denied

### ISSUE THREAD

**Issue by IsaacKailola** [geerlingguy/pi-webcam#68]
everyhing goes well until the uv-gadget needs to be cloned to the pi and i get this error.

fatal: [127.0.0.1] FAILED! => {"changed": false, "cmd" "/usr/bin/git clone --origin origin http://github.com/geerlingguy/uvc-gadget.git /home/pi/uvc-gadget", msg" : fatal: could not create leading directories of '/home/pi/unc-gadget' : Permission denied", "rc": 128, "stderr": "fatal: could not create leading directories of '/home/pi/uvc-gadget' : Pwemission dienied\n" "stdeer_lines": ["fatal: could not create leading directories of '/home/pi/unc-gadget': Permission dienied"], "stdout": "", "stdout_lines" : []}

**Comment by Deovi** [comment]
I had this issue and what it turned out to be is that the scrips are using the default 'pi' username. 

It's an easy fix. go to the task folder and edit the paths that start with '/home/pi/' to '/home/<the user you log in with>/'  and you should be good to go.
