### ISSUE TITLE
macOS 13.3.1 does not recognize pi-webcam

### ISSUE THREAD

**Issue by alexfilipidis** [geerlingguy/pi-webcam#76]
Hi Jeff,

I found that macOS doesn't recognize my pi-webcam that I replicated based on Raspberry Pi Zero 2 W. It works fine on Windows laptop, but macOS doesn't see that device.

Thank you,
Alex

**Comment by Ai-raspberrypi-gobrowse** [comment]
Hey, @alexfilipidis,
same here, I can't seem to find the problem
maybe use different cables?
I am using a raspberry pi zero

**Comment by Ai-raspberrypi-gobrowse** [comment]
update: i was looking at the yml and there were 2 files that said home/pi, is your username pi on your raspberry pi zero 2?

**Comment by alexfilipidis** [comment]
yes, I am using standard user, and web-cam did work with a previous macOS version
