### ISSUE TITLE
Issue installing PyYAML/Ansible (Solution)

### ISSUE THREAD

**Issue by Jrjy3** [geerlingguy/pi-webcam#77]
Running the `sudo pip3 install --no-binary pyyaml ansible` command resulted in errors while trying to install the cryptography dependency. For some reason, there are issues installing cryptography because it requires Rust to build, and it won't install a binary either.

To fix this, I ran `sudo pip3 install cryptography==3.1.1` to install a working binary of cryptography and then ran the above command again. It installed without issue.

**Comment by TSGames** [comment]
Thank you, run into exactly the same issue. I created a PR for the Readme
