### ISSUE TITLE
Adding a mic to the webcam

### ISSUE THREAD

**Issue by pranshumalik14** [geerlingguy/pi-webcam#8]
Hi,

I was wondering if it is possible to adapt the scripts you have to support an optional microphone, which would just work if you have it plugged in or have the same behavior as now if the mic's not connected. This will help make an all-in-one package for a decent performing pi webcam. I'm thinking of this [breakout board](https://www.adafruit.com/product/3421). 

Let me know, since I was thinking of making one of these. 

Thanks!

**Comment by geerlingguy** [comment]
I think it would be possible, but I also know it's a little outside my own expertise. For my own use, I don't need the mic as I use an external mic in all cases (or can settle for the built-in mic on my laptop). But it would be nice to have, especially for cases where the camera might be mounted in another room or outside, and the computer inside, or if you use it with a Raspberry Pi, like the Pi 400, which has no internal mic.

**Comment by pranshumalik14** [comment]
Makes sense. Is it possible to add a service that makes the audio available to the host device? This breakout board has some supporting libraries and after an install and reboot, the mic will be connected on boot

**Comment by pranshumalik14** [comment]
Maybe you can give me a few pointers to how I can add such a service if it's not possible to add in the changes right now. After testing it out I can make a pull request

**Comment by geerlingguy** [comment]
@pranshumalik14 - That would actually require changes to the uvc-gadget project that is used—see this file for starters: https://github.com/geerlingguy/uvc-gadget/blob/master/multi-gadget.sh

**Comment by pranshumalik14** [comment]
Thanks, I'll look into it!
