### ISSUE TITLE
clone uvc-gadget failed

### ISSUE THREAD

**Issue by tippy-somers** [geerlingguy/pi-webcam#84]
Am pretty new to this but would love to get this webcam working. I followed your read me file and got the following message.
Webcam will not work
Any help would be much appreciated.

 TASK [Clone uvc-gadget to the Pi.] *********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --o                            rigin origin https://github.com/geerlingguy/uvc-gadget.git /home/pi/uvc-gadget",                             "msg": "fatal: could not create leading directories of '/home/pi/uvc-gadget': P                            ermission denied", "rc": 128, "stderr": "fatal: could not create leading directo                            ries of '/home/pi/uvc-gadget': Permission denied\n", "stderr_lines": ["fatal: co                            uld not create leading directories of '/home/pi/uvc-gadget': Permission denied"]                            , "stdout": "", "stdout_lines": []}

**Comment by DarylWM** [comment]
This error is due to the Ansible tasks assuming your username is `pi`. Either switch to that username or edit the `piwebcam.yml` and `uvc-gadget.yml` tasks from `/home/pi/` to `/home/<username>/`. After that the tasks should work fine.
